# Processing parameters
jetR: [0.4]
alphas: [1, 1.5, 2, 3]

# For extra verbose output in some functions
debug_level: 0

process_observables: ['ang']
jet_matching_distance: 0.6        # Match jets with deltaR < jet_matching_distance*jetR

# Max eta value (for plots)
eta_max: 0.9

sd_zcut: 0.2
sd_beta: 0

###############################################################################
# Rebinning and unfolding parameters/configurations for angularity observables
ang:

  common_settings:
    xtitle: '#it{#lambda}_{#it{#alpha}}^{#it{#kappa}=1}'
    ytitle: '#frac{1}{#it{#sigma}_{jet}} #frac{d#it{#sigma}}{d#it{#lambda}_{#it{#alpha}}^{#it{#kappa}=1}}'
    pt_bins_reported: [10, 20, 40]
    plot_overlay_list:
      - ['config_R0.4_1', 'config_R0.4_1.5', 'config_R0.4_2', 'config_R0.4_3']
    #  - ['config_R0.4_1_SD', 'config_R0.4_1.5_SD', 'config_R0.4_2_SD', 'config_R0.4_3_SD']
    max_reg_param: 10

  ############################################################################
  # Different R & alpha configurations
  config_R0.4_1:
    R: 0.4
    alpha: 1
    pt_bins_truth:  [5, 10, 20, 40, 60, 80, 100, 150, 200]
    pt_bins_det: [5, 10, 15, 20, 25, 30, 40, 50, 60, 80, 100, 120, 150, 200]
    pt_bins_det_sys_truncation: [10, 15, 20, 25, 30, 40, 50, 60, 80, 100]
    obs_bins_truth:  [0.0, 0.08, 0.18, 0.28, 0.38, 0.52, 0.8]
    obs_max_reported: [0.52, 0.52]
    obs_bins_det: [0, 0.02, 0.05, 0.08, 0.1, 0.12, 0.14, 0.16, 0.18, 0.2, 0.22, 0.24,
                   0.26, 0.28, 0.3, 0.34, 0.38, 0.42, 0.46, 0.5, 0.6, 0.8]
    obs_bins_det_sys_binning: [0.0, 0.025, 0.05, 0.075, 0.1, 0.12, 0.15, 0.18, 0.2, 0.22,
                               0.25, 0.28, 0.3, 0.32, 0.35, 0.4, 0.45, 0.55, 0.8]
    reg_param:
      0.4: 5

  config_R0.4_1.5:
    R: 0.4
    alpha: 1.5
    pt_bins_truth:  [5, 10, 20, 40, 60, 80, 100, 150, 200]
    pt_bins_det: [5, 10, 15, 20, 25, 30, 40, 50, 60, 80, 100, 120, 150, 200]
    pt_bins_det_sys_truncation: [10, 15, 20, 25, 30, 40, 50, 60, 80, 100]
    obs_bins_truth:  [0.0, 0.04, 0.09, 0.15, 0.24, 0.35, 0.45, 0.7]
    obs_max_reported: [0.35, 0.35]
    obs_bins_det: [0, 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.1, 0.12,
                   0.14, 0.16, 0.18, 0.20, 0.22, 0.24, 0.28, 0.32, 0.38, 0.45, 0.5, 0.75]
    obs_bins_det_sys_binning: [0, 0.015, 0.03, 0.045, 0.06, 0.075, 0.09, 0.11, 0.13, 0.15,
                               0.17, 0.19, 0.21, 0.23, 0.26, 0.29, 0.33, 0.37, 0.48, 0.75]
    reg_param:
      0.4: 5

  config_R0.4_2:
    R: 0.4
    alpha: 2
    pt_bins_truth:  [5, 10, 20, 40, 60, 80, 100, 150, 200]
    pt_bins_det: [5, 10, 15, 20, 25, 30, 40, 50, 60, 80, 100, 120, 150, 200]
    pt_bins_det_sys_truncation: [10, 15, 20, 25, 30, 40, 50, 60, 80, 100]
    obs_bins_truth: [0.0, 0.025, 0.05, 0.09, 0.13, 0.18, 0.3, 0.35, 0.5, 0.7]
    obs_max_reported: [0.3, 0.3]
    obs_bins_det: [0, 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1, 0.11, 0.12,
                   0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.2, 0.22, 0.25, 0.3, 0.35, 0.4, 0.5, 0.7]
    obs_bins_det_sys_binning: [0, 0.015, 0.025, 0.035, 0.045, 0.055, 0.065, 0.075, 0.085, 0.1,
                   0.11, 0.13, 0.16, 0.18, 0.22, 0.25, 0.32, 0.37, 0.42, 0.55, 0.7]
    reg_param:
      0.4: 5

  config_R0.4_3:
    R: 0.4
    alpha: 3
    pt_bins_truth:  [5, 10, 20, 40, 60, 80, 100, 150, 200]
    pt_bins_det: [5, 10, 15, 20, 25, 30, 40, 50, 60, 80, 100, 120, 150, 200]
    pt_bins_det_sys_truncation: [10, 15, 20, 25, 30, 40, 50, 60, 80, 100]
    obs_bins_truth: [0.0, 0.01, 0.03, 0.05, 0.075, 0.12, 0.19, 0.25, 0.35, 0.5]
    obs_max_reported: [0.19, 0.19]
    obs_bins_det: [0, 0.002, 0.005, 0.008, 0.01, 0.015, 0.02, 0.025, 0.03, 0.035, 0.04, 0.045,
                   0.05, 0.055, 0.06, 0.065, 0.07, 0.075, 0.08, 0.09, 0.1, 0.12, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.5]
    obs_bins_det_sys_binning: [0, 0.003, 0.006, 0.009, 0.015, 0.025, 0.035, 0.045, 0.055, 
                               0.065, 0.075, 0.085, 0.095, 0.12, 0.16, 0.2, 0.26, 0.32, 0.42, 0.5]
    reg_param:
      0.4: 5

  ############################################################################
  # Different R & alpha configurations for SoftDrop
  #config_R0.4_1_SD:
  #  SoftDrop:
  #    zcut: 0.2
  #    beta: 0
  #  R: 0.4
  #  alpha: 1
  #  pt_bins_truth:  [5, 20, 40, 60, 80, 100, 150, 200]
  #  pt_bins_det: [5, 10, 15, 20, 25, 30, 40, 50, 60, 80, 100, 120, 150, 200]
  #  pt_bins_det_sys_truncation: [10, 15, 20, 25, 30, 40, 50, 60, 80, 100, 120]
  #  obs_bins_truth: [0, 0.03, 0.05, 0.07, 0.1, 0.15, 0.25, 0.4, 0.6, 0.8]
  #  obs_max_reported: [0.6]
  #  obs_bins_det: [0, 0.02, 0.04, 0.06, 0.09, 0.17, 0.25, 0.4, 0.6, 0.8]
  #  obs_bins_det_sys_binning: [0, 0.015, 0.03, 0.05, 0.1, 0.15, 0.25, 0.41, 0.58, 0.8]
  #  #reg_param:
  #  #  0.4: 3

  #config_R0.4_1.5_SD:
  #  SoftDrop:
  #    zcut: 0.2
  #    beta: 0
  #  R: 0.4
  #  alpha: 1.5
  #  pt_bins_truth:  [5, 20, 40, 60, 80, 100, 150, 200]
  #  pt_bins_det: [5, 10, 15, 20, 25, 30, 40, 50, 60, 80, 100, 120, 150, 200]
  #  pt_bins_det_sys_truncation: [10, 15, 20, 25, 30, 40, 50, 60, 80, 100, 120]
  #  obs_bins_truth: [0, 0.007, 0.015, 0.025, 0.05, 0.1, 0.15, 0.25, 0.5, 0.7]
  #  obs_max_reported: [0.5]
  #  obs_bins_det: [0, 0.007, 0.015, 0.025, 0.05, 0.1, 0.15, 0.25, 0.5, 0.7]
  #  obs_bins_det_sys_binning: [0, 0.005, 0.01, 0.02, 0.03, 0.045, 0.11, 0.16, 0.27, 0.53, 0.7]
  #  #reg_param:
  #  #  0.4: 3

  #config_R0.4_2_SD:
  #  SoftDrop:
  #    zcut: 0.2
  #    beta: 0
  #  R: 0.4
  #  alpha: 2
  #  pt_bins_truth:  [5, 20, 40, 60, 80, 100, 150, 200]
  #  pt_bins_det: [5, 10, 15, 20, 25, 30, 40, 50, 60, 80, 100, 120, 150, 200]
  #  pt_bins_det_sys_truncation: [10, 15, 20, 25, 30, 40, 50, 60, 80, 100, 120]
  #  obs_bins_truth: [0, 0.002, 0.008, 0.015, 0.025, 0.045, 0.085, 0.15, 0.35, 0.6]
  #  obs_max_reported: [0.35]
  #  obs_bins_det: [0, 0.002, 0.008, 0.015, 0.025, 0.045, 0.07, 0.1, 0.15, 0.2, 0.35, 0.6]
  #  obs_bins_det_sys_binning: [0, 0.003, 0.009, 0.015, 0.03, 0.05, 0.075, 0.1, 0.16, 0.21, 0.33, 0.6]
  #  #reg_param:
  #  #  0.4: 3

  #config_R0.4_3_SD:
  #  SoftDrop:
  #    zcut: 0.2
  #    beta: 0
  #  R: 0.4
  #  alpha: 3
  #  pt_bins_truth:  [5, 20, 40, 60, 80, 100, 150, 200]
  #  pt_bins_det: [5, 10, 15, 20, 25, 30, 40, 50, 60, 80, 100, 120, 150, 200]
  #  pt_bins_det_sys_truncation: [10, 15, 20, 25, 30, 40, 50, 60, 80, 100, 120]
  #  obs_bins_truth: [0, 0.001, 0.003, 0.008, 0.015, 0.03, 0.06, 0.1, 0.25, 0.5]
  #  obs_max_reported: [0.25]
  #  obs_bins_det: [0, 0.001, 0.003, 0.008, 0.015, 0.03, 0.06, 0.1, 0.25, 0.5]
  #  obs_bins_det_sys_binning: [0, 0.003, 0.015, 0.035, 0.07, 0.11, 0.24, 0.5]
  #  #reg_param:
  #  #  0.4: 3


###############################################################################
# Analysis & plotting parameters
file_format: ".pdf"
output_dir: "/rstorage/alice/AnalysisResults/ang/pp/pTcut/AngR04_D0_baseline"
roounfold_path: "/home/ezra/heppy/external/roounfold/roounfold-current/lib/libRooUnfold.so"

analysis_observable: 'ang'
do_unfolding: False
force_rebin: False
do_systematics: True
do_plot_final_result: True
do_plot_performance: False
figure_approval_status: 'Work In Progress'

# Whether or not to use the previous measurement in ratio
use_prev_result: False

# List of which systematics to perform
# Options: [main, trkeff, prior1, prior2, truncation, binning, \
#           random_mass, fastsim_generator0, fastsim_generator1]
systematics_list:
  - main
  - trkeff
  - prior1
  - prior2
  - truncation
  - binning
  - random_mass
  - fastsim_generator0
  - fastsim_generator1
#  - fastsim_generator2

# Paths to processing output, to be used for unfolding
main_data: '/rstorage/alice/AnalysisResults/ang/1163212/AnalysisResultsFinal.root'
main_response: '/rstorage/alice/AnalysisResults/ang/1191459/Scaled_no_cuts/AnalysisResultsFinal.root'
trkeff_response: '/rstorage/alice/AnalysisResults/ang/1191462/Scaled_no_cuts/AnalysisResultsFinal.root'
randmass_data: '/rstorage/alice/AnalysisResults/ang/1191200/AnalysisResultsFinal.root'
randmass_response: '/rstorage/alice/AnalysisResults/ang/1191466/Scaled_no_cuts/AnalysisResultsFinal.root'
# fastsim order: PYTHIA, Herwig
fastsim_response: ['/rstorage/alice/AnalysisResults/ang/1191463/Scaled_no_cuts/AnalysisResultsFinal.root',
                   '/rstorage/alice/AnalysisResults/ang/1191464/Scaled_no_cuts/AnalysisResultsFinal.root']

# Prior variation parameters
prior_variation_option: 1
prior1_variation_parameter: 0.5
prior2_variation_parameter: -0.5
